# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e7cad2b8b072eddb828ab52fde0672daa955ff4592e8ea971e33f08e728638e9ec353f4c79741e4dfb754979f8697c4de9abccce2259ab1ecd1cc8a6ae97549

test:
  secret_key_base: 15d442b1ebff77abed6c3b5ea17866f695da59df8f12ef82aa71e0ce93ff875341c365ff826c8647cd7bbd57f15a0ce63014bb7526e0395b30a4ac9853ee5f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
